// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZkN3F5j8HHc4JhQ8VkGclKL7M1BfxOJU',
    appId: '1:1006723116792:web:0e4b37ba4b94b59ffe950d',
    messagingSenderId: '1006723116792',
    projectId: 'flutterfirestarter',
    authDomain: 'flutterfirestarter.firebaseapp.com',
    storageBucket: 'flutterfirestarter.firebasestorage.app',
    measurementId: 'G-7HGT76HKVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEGhqIEWnW5zyt1I3TY_2revjlc1JYNr0',
    appId: '1:1006723116792:android:3b0b286b41f367c5fe950d',
    messagingSenderId: '1006723116792',
    projectId: 'flutterfirestarter',
    storageBucket: 'flutterfirestarter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6euQEHUIsSEgs9-Lf7l9N7ILcsHi1gSw',
    appId: '1:1006723116792:ios:b3af2cb7e59022c0fe950d',
    messagingSenderId: '1006723116792',
    projectId: 'flutterfirestarter',
    storageBucket: 'flutterfirestarter.firebasestorage.app',
    iosClientId: '1006723116792-3diql33kpch1ssm9t867dtudl337e7e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartlifeorganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6euQEHUIsSEgs9-Lf7l9N7ILcsHi1gSw',
    appId: '1:1006723116792:ios:b3af2cb7e59022c0fe950d',
    messagingSenderId: '1006723116792',
    projectId: 'flutterfirestarter',
    storageBucket: 'flutterfirestarter.firebasestorage.app',
    iosClientId: '1006723116792-3diql33kpch1ssm9t867dtudl337e7e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartlifeorganizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZkN3F5j8HHc4JhQ8VkGclKL7M1BfxOJU',
    appId: '1:1006723116792:web:015e54a932383781fe950d',
    messagingSenderId: '1006723116792',
    projectId: 'flutterfirestarter',
    authDomain: 'flutterfirestarter.firebaseapp.com',
    storageBucket: 'flutterfirestarter.firebasestorage.app',
    measurementId: 'G-RXXGB7R21F',
  );
}
